"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from .address import *
from .company_read import *
from .contract_automaticrenewal import *
from .contract_collection import *
from .contract_phase import *
from .contract_read import *
from .contract_renewal import *
from .contract_termination import *
from .contract_write import *
from .contractdocument_read import *
from .contracttype_collection import *
from .contracttype_read import *
from .contracttypename_read import *
from .customfield_collection import *
from .customfield_read import *
from .customfieldvalue_read import *
from .customfieldvalue_write import *
from .department_collection import *
from .department_read import *
from .department_write import *
from .document_collection import *
from .document_read import *
from .document_write import *
from .documentversion_read import *
from .dossier_collection import *
from .dossier_read import *
from .legalentity_collection import *
from .legalentity_read import *
from .office_collection import *
from .office_read import *
from .office_write import *
from .pagination import *
from .relation_collection import *
from .relation_read import *
from .relation_write import *
from .security import *
from .task_collection import *
from .task_read import *
from .task_update import *
from .task_write import *
from .user_collection import *
from .user_current import *
from .user_read import *

__all__ = ["Address","CompanyRead","ContractAutomaticRenewal","ContractCollection","ContractDocumentRead","ContractPhase","ContractRead","ContractRenewal","ContractTermination","ContractTypeCollection","ContractTypeNameRead","ContractTypeRead","ContractWrite","CustomFieldCollection","CustomFieldRead","CustomFieldValueRead","CustomFieldValueWrite","DepartmentCollection","DepartmentRead","DepartmentWrite","DocumentCollection","DocumentRead","DocumentVersionRead","DocumentWrite","DossierCollection","DossierRead","DueDateDependsOn","LegalEntityCollection","LegalEntityRead","OfficeCollection","OfficeRead","OfficeWrite","Pagination","RelationCollection","RelationRead","RelationWrite","Role","Security","Status","TaskCollection","TaskRead","TaskUpdate","TaskUpdateDueDateDependsOn","TaskUpdateStatus","TaskWrite","TaskWriteDueDateDependsOn","TaskWriteStatus","UserCollection","UserCurrent","UserRead"]
