"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from contractifyproduction import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Optional



@dataclasses.dataclass
class DeleteDepartmentRequest:
    company: int = dataclasses.field(metadata={'path_param': { 'field_name': 'company', 'style': 'simple', 'explode': False }})
    r"""Id of the company"""
    department: int = dataclasses.field(metadata={'path_param': { 'field_name': 'department', 'style': 'simple', 'explode': False }})
    r"""Id of the department"""
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class DeleteDepartment404ApplicationJSON:
    r"""Not Found"""
    message: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message'), 'exclude': lambda f: f is None }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class DeleteDepartment403ApplicationJSON:
    r"""Forbidden"""
    message: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message'), 'exclude': lambda f: f is None }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class DeleteDepartment401ApplicationJSON:
    r"""Unauthenticated"""
    message: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message'), 'exclude': lambda f: f is None }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class DeleteDepartment400ApplicationJSON:
    r"""Precondition failed"""
    message: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message'), 'exclude': lambda f: f is None }})
    




@dataclasses.dataclass
class DeleteDepartmentResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    delete_department_400_application_json_object: Optional[DeleteDepartment400ApplicationJSON] = dataclasses.field(default=None)
    r"""Precondition failed"""
    delete_department_401_application_json_object: Optional[DeleteDepartment401ApplicationJSON] = dataclasses.field(default=None)
    r"""Unauthenticated"""
    delete_department_403_application_json_object: Optional[DeleteDepartment403ApplicationJSON] = dataclasses.field(default=None)
    r"""Forbidden"""
    delete_department_404_application_json_object: Optional[DeleteDepartment404ApplicationJSON] = dataclasses.field(default=None)
    r"""Not Found"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

